import { style } from "@mui/system";
import type { NextPage } from "next";
import Head from "next/head";
import Page from "../components/Page";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Tribute page | Norman Borlaug</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700;900&display=swap"
          rel="stylesheet"
        />
      </Head>
      <Page />
    </div>
  );
};

export default Home;
